Binary search
VamsiSangam/theoryofprogramming pull request #47
Opened 2017-04-09 09:55 UTC by salman-bhai

This pull request is for issue number #19 

### Brief description about contribution
* Binary Search Algorithm added using iterative version. 
* Vectors used instead of the conventional arrays.

2017-04-09 09:55 UTC, salman-bhai commented
@VamsiSangam kindly take a look!

2017-04-09 10:03 UTC, salman-bhai commented
Kindly merge all the commits!
Sorry for the mess! First contribution that's why! :see_no_evil:

2017-04-14 05:09 UTC, VamsiSangam reviewed
Code runs fine! Requested minor changes.

2017-04-14 05:09 UTC, VamsiSangam commented on Searching Algorithms/Binary Search Algorithm/C++/binary-search.cpp
> +		int mid = ((first+last)/2);
Spaces on both sides of each binary operator please.

2017-04-14 05:09 UTC, VamsiSangam commented on Searching Algorithms/Binary Search Algorithm/C++/binary-search.cpp
> +		else
Do add braces here for better readability.

2017-04-14 05:09 UTC, VamsiSangam commented on Searching Algorithms/Binary Search Algorithm/C++/binary-search.cpp
> +	else
Add curly braces here too.

2017-04-14 05:09 UTC, VamsiSangam commented on Searching Algorithms/Binary Search Algorithm/C++/binary-search.cpp
> +		printf("Key found at position %d\n",x+1);
Spaces for binary operator.

2017-04-15 14:40 UTC, ranesr requested changes

2017-04-15 14:40 UTC, ranesr commented on Searching Algorithms/Binary Search Algorithm/C++/binary-search.cpp
> +//Main Binary Search logic
Can you please update all comments like?
```
// Main Binary Search logic
```

2017-04-16 03:40 UTC, salman-bhai commented
Changes made as per suggestions by @ranesr

2017-04-16 04:45 UTC, VamsiSangam reviewed
Actually @ranesr meant to add a space before starting a comment. So, your comments should look like this -

```
// Main binary search logic
```

and not like this -

```
//Main binary search logic
```

You can find more info about the coding conventions in [CONVENTIONS.md](https://github.com/VamsiSangam/theoryofprogramming/blob/master/CONVENTIONS.md) :smile:

2017-04-16 12:13 UTC, salman-bhai commented
How about now :sweat_smile:

2017-04-16 13:07 UTC, VamsiSangam approved these changes
LGTM :+1:

2017-04-16 13:08 UTC, VamsiSangam commented
We mind a lot about the readability, so don't mind the reminders about the conventions :stuck_out_tongue_closed_eyes:

2017-04-16 13:09 UTC, VamsiSangam commented
Thanks for your contribution, you should be able to see your code live on the [corresponding post](http://theoryofprogramming.com/2016/11/04/binary-search-algorithm/), in a few minutes.

2017-04-16 13:09 UTC, merged

2017-04-16 13:17 UTC, VamsiSangam commented
I must have overlooked it. We really want the vector to be a local variable, being passed to binary search method as function parameters. I have opened an issue for that. Please work on #48 when free. :smile: