Jump Search in C++
VamsiSangam/theoryofprogramming pull request #54
Opened 2017-08-13 16:44 UTC by praveenmylavarapu

This pull request is for issue number #20

2017-08-13 17:16 UTC, VamsiSangam requested changes
Code seems to work fine, but you implementation must resemble the other existing implementations as much as possible, eg. in terms of return values.

Try to have a look at the other implementations and keep your code familiar to it.

Also, you seem to have written code with the aim of reducing number of lines. Short code is often not easy to read. As this code will be displayed on a tutorial website, your code must be easily understandable. It is okay if you lengthen your code with full proper loops, comments or some extra code, it will only improve understand-ability.

Also, no need for the input/output test case files here, as we will show some cases in the main method itself.

2017-08-13 17:16 UTC, VamsiSangam commented on Searching Algorithms/Jump Search Algorithm/C++/JumpSearch.cpp
> +    int a[100], i = 0, n, value;
Don't use fixed size arrays. Demo arrays such as `int a[] = {2, 4, 6, 8, 9, 12}` are fine.

2017-08-13 17:16 UTC, VamsiSangam commented on Searching Algorithms/Jump Search Algorithm/C++/JumpSearch.cpp
> +bool jumpSearch(int a[100], int n, int value)
`int arr[]` must be the parameter. Return type must be `int`

2017-08-13 17:16 UTC, VamsiSangam commented on Searching Algorithms/Jump Search Algorithm/C++/JumpSearch.cpp
> +    return 1;
Return `-1` here.

2017-08-13 17:16 UTC, VamsiSangam commented on Searching Algorithms/Jump Search Algorithm/C++/JumpSearch.cpp
> +    cout << "Found!" << endl;
You can just print the return value of `jumpSearch()`. Make multiple calls on same function to show different cases, like the other implementations.

2017-08-13 18:27 UTC, praveenmylavarapu commented
I made the requested changes.
Should my implementation resemble the other existing implementations as much as possible in terms of logic also? Mine is actually simple and it does Linear Search Backwards as described in the image of the article.
And should I use braces for single line loops and conditionals?

2017-08-14 06:01 UTC, VamsiSangam requested changes
Minor cosmetic changes requested.

2017-08-14 06:01 UTC, VamsiSangam commented on Searching Algorithms/Jump Search Algorithm/C++/JumpSearch.cpp
> +    for (i = 0; i + jump < n && arr[i] < value; i += jump);
Insert the comment inside this loop, and break the long comment into multiple lines. Eg. -

``` c
for (...) {
    // Keep jumping until value is between any two
    // elements of the array or when i goes out of bound
}
```

2017-08-14 06:01 UTC, VamsiSangam commented on Searching Algorithms/Jump Search Algorithm/C++/JumpSearch.cpp
> +    if (value <= arr[i])    // right is i if search value is less than any jumped element in the array. If not, right is last element
Here too, insert the comment inside the `if`. Eg. -

``` c
if (value <= arr[i]) {
    // right is i if search value is less than
    // any jumped element in the array.
    right = i;
}
```

2017-08-14 06:01 UTC, VamsiSangam commented on Searching Algorithms/Jump Search Algorithm/C++/JumpSearch.cpp
> +    left = right - jump;
Use `left = max(right - jump, 0)` instead. Also add the comment `// ensuring left doesn't go negative` next to it.

2017-08-14 06:01 UTC, VamsiSangam commented on Searching Algorithms/Jump Search Algorithm/C++/JumpSearch.cpp
> +    int arr[] = {1, 3, 5, 7, 9, 11, 13, 15}, n = sizeof(arr)/sizeof(int);
Write the declaration of `n` in a new line.

2017-08-14 09:36 UTC, VamsiSangam requested changes

2017-08-14 09:36 UTC, VamsiSangam commented on Searching Algorithms/Jump Search Algorithm/C++/JumpSearch.cpp
> +    else {
`// If not, right is last element` in the previous comment will come under this else, not in the `if` clause. Also please correct the brackets. The code should be -

``` c
    if (value <= arr[i]) {
        // right is i if search value is less than
        // any jumped element in the array.
        right = i;
    } else {
        // If not, right is last element
        right = n;
    }
```

2017-08-14 09:36 UTC, VamsiSangam commented on Searching Algorithms/Jump Search Algorithm/C++/JumpSearch.cpp
> +    left = max(right - jump, 0);    // ensuring left dosen't go negaitive
Correct spellings :stuck_out_tongue_closed_eyes: 

> ensuring left **doesn't** go **negative**

2017-08-14 09:36 UTC, VamsiSangam commented on Searching Algorithms/Jump Search Algorithm/C++/JumpSearch.cpp
> +    int n = sizeof(arr)/sizeof(int);
Add space on either side of `/` operator.

2017-08-14 09:47 UTC, praveenmylavarapu commented
Sorry for my silly mistakes and thank you for your patience @VamsiSangam

2017-08-14 09:53 UTC, VamsiSangam requested changes
Minor cosmetic changes requested.

2017-08-14 09:53 UTC, VamsiSangam commented on Searching Algorithms/Jump Search Algorithm/C++/JumpSearch.cpp
> +#include <math.h>
Change this to `cmath`

2017-08-14 09:53 UTC, VamsiSangam commented on Searching Algorithms/Jump Search Algorithm/C++/JumpSearch.cpp
> +    while (right >= left)
Add `{ }` here

2017-08-14 09:53 UTC, VamsiSangam commented on Searching Algorithms/Jump Search Algorithm/C++/JumpSearch.cpp
> +        if (arr[right--] == value)
Add `{ }` here

2017-08-15 05:00 UTC, VamsiSangam approved these changes
LGTM :+1:

2017-08-15 05:01 UTC, merged

2017-08-15 05:05 UTC, VamsiSangam commented
Thanks for your contribution! You should be able to see your code live on the [corresponding post](http://theoryofprogramming.com/2016/11/10/jump-search-algorithm/). :smile: